class ZCL_INFOCOCKPIT_SERVICES definition
  public
  final
  create public .

public section.

  class-data SENDE_INFOMAIL type FLAG .

  class-methods GET_KOMMUNIKDATEN_LIEFERANT
    importing
      !ID_LIFNR type LIFNR
    exporting
      !ED_TELF1 type TELF1
      !ED_TELFX type TELFX
      !ED_SMTP_ADDR type AD_SMTPADR .
  class-methods SENDE_INFO_EMAIL
    importing
      !IS_INFO_CONTEXT type ZST_INFO_CONTEXT
      !IS_INFO_ZUSATZ type ZST_INFO_CONTEXT_ZUSATZ
      !IF_IN_UPDATE_TASK type ABAP_BOOL default ABAP_TRUE
    exceptions
      ERROR .
protected section.
private section.
ENDCLASS.



CLASS ZCL_INFOCOCKPIT_SERVICES IMPLEMENTATION.


  METHOD GET_KOMMUNIKDATEN_LIEFERANT.

    SELECT LF~TELF1,
           LF~TELFX,
           ADR~\_DEFAULTEMAILADDRESS-EMAILADDRESS AS SMTP_ADDR
           FROM LFA1 AS LF LEFT OUTER JOIN I_ADDRESS AS ADR ON
                LF~ADRNR = ADR~ADDRESSID
           WHERE LIFNR = @ID_LIFNR
           INTO @DATA(LS_ADDRESS) UP TO 1 ROWS.
    ENDSELECT.

    ED_TELF1 = LS_ADDRESS-TELF1.
    ED_TELFX = LS_ADDRESS-TELFX.
    ED_SMTP_ADDR = LS_ADDRESS-SMTP_ADDR.

  ENDMETHOD.


METHOD SENDE_INFO_EMAIL.

  DATA:
    LT_TEXT TYPE ZCL_ADMIN_SERVICES=>LT_TEXT,
    LS_TEXT LIKE LINE OF LT_TEXT.
  DATA: LT_NOTE         TYPE BCSY_TEXT,
        LT_ADDRESS_MAIL TYPE ZCL_ADMIN_SERVICES=>T_ADDESSES,
        LS_ADDRESS_MAIL LIKE LINE OF LT_ADDRESS_MAIL,
        LT_ADDRESS_SAP  TYPE ZCL_ADMIN_SERVICES=>T_ADDRESS_USER,
        LS_ADDRESS_SAP  LIKE LINE OF LT_ADDRESS_SAP,
        LT_FILE         TYPE ZCL_ADMIN_SERVICES=>LT_FILE.
  DATA: LD_RECIPIENT TYPE SY-UNAME,
        LT_ZUSERKZ   TYPE Z_T_ZUSERKZ,
        LD_ZUSERKZ   TYPE ZUSERKZ.
  DATA: " LD_TITLE   TYPE STRING,
    ID_BETREFF TYPE STRING,
    LD_ADRLINE TYPE STRING,
    LD_IDENT   TYPE STRING.
  DATA: MS_ADDRESS TYPE BAPIADDR3,
        RETURN     TYPE STANDARD TABLE OF BAPIRET2.
  DATA: ED_DATE_STRING TYPE STRING,
        LD_STRING      TYPE STRING,
        LD_STRING_NAME TYPE STRING,
        DUMMY          TYPE STRING.

  CONSTANTS:
  LC_BCS_RQST      TYPE BCS_RQST VALUE 'N'.

  DATA: GD_TEXT_UPDATE TYPE STRING,
        LD_DATE_C(10)  TYPE C.
  DATA: IT_ROLLE TYPE BUP_T_ROLE,
        LS_ROLLE LIKE LINE OF IT_ROLLE.
  DATA: ET_MV_PARTNER TYPE Z_T_ZVCNBPADRESS,
        LS_MV_PARTNER LIKE LINE OF ET_MV_PARTNER.

  DATA ES_PARTNER        TYPE ZST_VTMDT_PARTNER.




  " Set Betreff
  IF SY-SYSID = 'PS4'.
    ID_BETREFF = |Notdienstportal Meld. { IS_INFO_ZUSATZ-NEW_QMNUM ALPHA = OUT } { IS_INFO_ZUSATZ-ADTXTZUS }| ##NO_TEXT.
  ELSE.
    ID_BETREFF = |TEST!!! { SY-SYSID } Notdienstportal Meld. { IS_INFO_ZUSATZ-NEW_QMNUM ALPHA = OUT } { IS_INFO_ZUSATZ-ADTXTZUS }| ##NO_TEXT.
  ENDIF.


* Set Text
  CLEAR LS_TEXT.


  LS_TEXT = |Folgende PM-Meldung { IS_INFO_ZUSATZ-NEW_QMNUM ALPHA = OUT } { IS_INFO_ZUSATZ-COD_TXTZUS } wurde aus Notdienstportal am { SY-DATUM DATE = USER } angelegt.|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.
  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.


  CLEAR LS_TEXT.
  LS_TEXT = |Objektdaten:|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Buchungskreis:       { IS_INFO_ZUSATZ-BUKRSZUS ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Wirtschaftseinheit:  { IS_INFO_ZUSATZ-SWENRZUS ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Gebäude:             { IS_INFO_ZUSATZ-SGENRZUS ALPHA = OUT } |.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Grundstück:          { IS_INFO_ZUSATZ-SGENRZUS ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Mieteinheit:         { IS_INFO_ZUSATZ-SMENRZUS ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Geschoss:            { IS_INFO_ZUSATZ-XSTOCKL ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Lage im Geschoss:    { IS_INFO_ZUSATZ-XMLGESCH ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.


  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.


  CLEAR LS_TEXT.
  LS_TEXT = |Mieterdaten:|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Vertrag:             { IS_INFO_ZUSATZ-RECNNR ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Vorname:             { IS_INFO_ZUSATZ-NAME_FIRSTPAR ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Name:                { IS_INFO_ZUSATZ-NAME_LASTPAR ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Straße/Nummer:       { IS_INFO_ZUSATZ-STREETPAR } { IS_INFO_ZUSATZ-HOUSE_NUM1PAR } |.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |PLZ/Ort:             { IS_INFO_ZUSATZ-POST_CODE1PAR } { IS_INFO_ZUSATZ-CITY1PAR }|.
  APPEND LS_TEXT TO LT_TEXT.


  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.


  CLEAR LS_TEXT.
  LS_TEXT = |Zusatzdaten:|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  LS_TEXT = |Techn. Platz:        { IS_INFO_ZUSATZ-TPLNRZUS ALPHA = OUT }|.
  APPEND LS_TEXT TO LT_TEXT.

  CLEAR LS_TEXT.
  IF IS_INFO_ZUSATZ-BUKRSZUS IS NOT INITIAL AND
    IS_INFO_ZUSATZ-SWENRZUS IS NOT INITIAL AND
    IS_INFO_ZUSATZ-SGENRZUS IS NOT INITIAL AND
    IS_INFO_ZUSATZ-SMENRZUS IS INITIAL.
    LS_TEXT = |Techn. Objekt:     { IS_INFO_ZUSATZ-BUKRSZUS  }/{ IS_INFO_ZUSATZ-SWENRZUS  }/{ IS_INFO_ZUSATZ-SGENRZUS  }|.

  ELSEIF IS_INFO_ZUSATZ-BUKRSZUS IS NOT INITIAL AND
    IS_INFO_ZUSATZ-SWENRZUS IS NOT INITIAL AND
    IS_INFO_ZUSATZ-SGENRZUS IS NOT INITIAL AND
    IS_INFO_ZUSATZ-SMENRZUS IS NOT INITIAL.
    LS_TEXT = |Techn. Objekt:     { IS_INFO_ZUSATZ-BUKRSZUS  }/{ IS_INFO_ZUSATZ-SWENRZUS }/{ IS_INFO_ZUSATZ-SGENRZUS  }/{ IS_INFO_ZUSATZ-SMENRZUS ALPHA = OUT }|.

*  ELSEIF IS_INFO_ZUSATZ-BUKRSZUS IS NOT INITIAL AND
*    IS_INFO_ZUSATZ-SWENRZUS IS NOT INITIAL AND
*    IS_INFO_ZUSATZ-SGRNRZUS IS NOT INITIAL AND
*    IS_INFO_ZUSATZ-SMENRZUS IS INITIAL.
*    LS_TEXT = |Techn. Objekt:       { IS_INFO_ZUSATZ-BUKRSZUS ALPHA = OUT }/{ IS_INFO_ZUSATZ-SWENRZUS ALPHA = OUT }/{ IS_INFO_ZUSATZ-SGRNRZUS ALPHA = OUT }|.
*
*  ELSEIF IS_INFO_ZUSATZ-BUKRSZUS IS NOT INITIAL AND
*  IS_INFO_ZUSATZ-SWENRZUS IS NOT INITIAL AND
*  IS_INFO_ZUSATZ-SGRNRZUS IS NOT INITIAL AND
*  IS_INFO_ZUSATZ-SMENRZUS IS NOT INITIAL.
*    LS_TEXT = |Techn. Objekt:       { IS_INFO_ZUSATZ-BUKRSZUS ALPHA = OUT }/{ IS_INFO_ZUSATZ-SWENRZUS ALPHA = OUT }/{ IS_INFO_ZUSATZ-SGRNRZUS ALPHA = OUT }/{ IS_INFO_ZUSATZ-SMENRZUS ALPHA = OUT }|.
  ENDIF.
  APPEND LS_TEXT TO LT_TEXT.


  CLEAR LS_TEXT.
  LS_TEXT = |Schadenscodierung:   { IS_INFO_ZUSATZ-MNGRPZUS ALPHA = OUT }/{ IS_INFO_ZUSATZ-MNCODZUS ALPHA = OUT } Bez. { IS_INFO_ZUSATZ-GES_TXTZUS }|.
  APPEND LS_TEXT TO LT_TEXT.


  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.

  IF IS_INFO_ZUSATZ-T_LTEXTZUS[] IS NOT INITIAL.
    CLEAR LS_TEXT.
    LS_TEXT = |Langtext zum Schaden:|.
    APPEND LS_TEXT TO LT_TEXT.

    CLEAR LS_TEXT.
    APPEND LS_TEXT TO LT_TEXT.

    LOOP AT IS_INFO_ZUSATZ-T_LTEXTZUS INTO DATA(LS_TEXTZUS).
      CLEAR LS_TEXT.
      LS_TEXT = LS_TEXTZUS.
      APPEND LS_TEXT TO LT_TEXT.
    ENDLOOP.
  ENDIF.


  CLEAR LS_TEXT.
  APPEND LS_TEXT TO LT_TEXT.

  LS_TEXT = 'Dieses Schreiben wurde maschinell erstellt'  ##NO_TEXT.
  APPEND LS_TEXT TO LT_TEXT.




  DATA: LD_EMAL_SOFORT TYPE FLAG.
  DATA IT_ADDRESSES    TYPE ZCL_ISCN_WF_NOTICE=>T_ADDESSES.
  DATA IT_ADDRESSES_CC TYPE ZCL_ISCN_WF_NOTICE=>T_ADDESSES.

  " Set Adress
  APPEND IS_INFO_CONTEXT-AN TO LT_ADDRESS_MAIL.

  SPLIT IS_INFO_CONTEXT-CC AT ';' INTO TABLE IT_ADDRESSES_CC.

  IF IS_INFO_CONTEXT-CC_LUBITZ IS NOT INITIAL.
    APPEND IS_INFO_CONTEXT-CC_LUBITZ_EMAIL TO IT_ADDRESSES_CC.
  ENDIF.

  ZCL_ADMIN_SERVICES=>EMAIL_SENDEN_NEU_CONVERT(
   EXPORTING
     ID_BETREFF       = ID_BETREFF
     IT_TEXT          = LT_TEXT
     IT_ADDRESSES     = LT_ADDRESS_MAIL
     IT_ADDRESSES_CC  = IT_ADDRESSES_CC
     IT_FILE          = LT_FILE
     IF_COMMIT_WORK   = IF_IN_UPDATE_TASK
     ID_BCS_RQST      = LC_BCS_RQST
     IT_ADDRESS_USER   = LT_ADDRESS_SAP
     ID_SENDER        = 'ZBATCH'
   EXCEPTIONS
     ERROR        = 1
     OTHERS       = 2
     ).
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
    WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4
    RAISING ERROR.
  ENDIF.



ENDMETHOD.
ENDCLASS.
