
PROCESS BEFORE OUTPUT.
  MODULE STATUS_5000.
  CALL SUBSCREEN ZUSATZ_CUST   INCLUDING
                  GX_KC->S_SCREENS-PROG_ZUSATZ_CUST
                  GX_KC->S_SCREENS-SCR_ZUSATZ_CUST
                .
  MODULE PBO_5000.                       " EF CH2411-0044
  CALL SUBSCREEN INFO_EMAIL INCLUDING    " EF CH2411-0044
                 GS_GUI-SUBSCREEN-REPID  " EF CH2411-0044
                 GS_GUI-SUBSCREEN-DYNNR. " EF CH2411-0044


*
PROCESS AFTER INPUT.
  FIELD GX_KC->S_ZUSATZ-TPLNR MODULE READ_TPNAME ON REQUEST.

  CHAIN.
    FIELD GX_KC->S_ZUSATZ-MNGRP.
    FIELD GX_KC->S_ZUSATZ-MNCOD.
    MODULE NEW_CODE ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD GX_KC->S_ZUSATZ-IDNRK.
    FIELD GX_KC->S_ZUSATZ-MAKTX.
    MODULE NEW_IDNRK ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD GX_KC->S_ZUSATZ-EQUNR.
    MODULE NEW_EQUNR ON CHAIN-REQUEST.
  ENDCHAIN.

  CALL SUBSCREEN ZUSATZ_CUST.
  CALL SUBSCREEN INFO_EMAIL . " EF CH2411-0044

  MODULE USER_COMMAND_5000.
