FUNCTION-POOL ZRE_PM_COCKPIT.             "MESSAGE-ID ..

* Datendeklarationen global
INCLUDE /DATRAIN/KC_MAIN_08_TOP.
CONSTANTS:
GC_ANWENDUNG_2 TYPE /DATRAIN/AL_DE_ANWENDUNG VALUE 'KW'. "KW = WebKundencenter, um GRID = C zu setzten

DATA: GO_ALV_CLERK       TYPE REF TO CL_SALV_TABLE,
      GO_ALV_PARTNER     TYPE REF TO CL_SALV_TABLE,
      GO_ALV_COND        TYPE REF TO CL_SALV_TABLE,
      GO_ALV_AREA        TYPE REF TO CL_SALV_TABLE,
      GO_ALV_OCCUPANCY   TYPE REF TO CL_SALV_TABLE,
      GO_ALV_NOTDIENST   TYPE REF TO CL_SALV_TABLE,
      GO_ALV_WARTUNG     TYPE REF TO CL_SALV_TABLE,
      GO_ALV_WARTUNG_GEB TYPE REF TO CL_SALV_TABLE,
      GO_ALV_WARTUNG_WE  TYPE REF TO CL_SALV_TABLE,
      GO_ALV_BESTELLUNG  TYPE REF TO CL_SALV_TABLE,
      GO_ALV_CHARACT     TYPE REF TO CL_SALV_TABLE,
      GO_ALV_CHARACT_RO  TYPE REF TO CL_SALV_TABLE,
      GO_ALV_CHARACT_WE  TYPE REF TO CL_SALV_TABLE,
      GO_ALV_RO          TYPE REF TO CL_SALV_TABLE,
      GO_ALV_KESSEL      TYPE REF TO CL_SALV_TABLE.
DATA:
  GO_CC_RECN        TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "weitere Verträge
  GO_CC_PARTNER     TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
  GO_CC_CLERK       TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Ansprechpartner
  GO_CC_OCCUPANCY   TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Belegung
  GO_CC_WARTUNG     TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Wartungspläne Mietobjekt
  GO_CC_NOTDIENST   TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Notdienst
  GO_CC_WARTUNG_GEB TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Wartungspläne Gebäude
  GO_CC_WARTUNG_WE  TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Wartungspläne Wirtschaftseinheit
  GO_CC_CHARACT     TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Aussattungsmerkmale Gebäude
  GO_CC_CHARACT_RO  TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Aussattungsmerkmale Mietobjekt
  GO_CC_RO          TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Objekte pro Gebäude
  GO_CC_KESSEL      TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Kessel angeschlossen Objekte
  GO_CC_RECNBTN     TYPE REF TO CL_GUI_CUSTOM_CONTAINER, "Immoakte
  GO_CC_BESTELLUNG  TYPE REF TO CL_GUI_CUSTOM_CONTAINER. "Bestellung Wirtschaftseinheit

* allgemeine Strukturen
TYPES: BEGIN OF TT_RECN,
         INTRENO        TYPE RECAINTRENO,
         BUKRS          TYPE BUKRS,
         BUTXT          TYPE BUTXT,
         RECNNR         TYPE RECNNUMBER,
         RECNTYPE       TYPE RECNCONTRACTTYPE,
         RECNBEG        TYPE RECNCNBEG,
         RECNENDABS(10),   "TYPE recncnendabs,
         RECNTXT        TYPE RECNTXT,
         SWENR          TYPE  SWENR,
         XWETEXT        TYPE REBDXBE,
         SGENR          TYPE  SGENR,
         XGETXT         TYPE REBDXBU,
         SMENR          TYPE  SMENR,
         XMETXT         TYPE REBDXRO,
         ZZSGEBT        TYPE XGEBK,
         JDENKMAL       TYPE JDENKMAL, "Denkmalschutz
         ZZPORTFOLIO    TYPE Z_PORTFOLIONAME, "Portfolio
         KDST           TYPE ZKUNDEN_D_STELLE, "Kundendiesnstelle
         AUFZUG         TYPE RECABOOL, "Aufzug vorhanden?
         WEG            TYPE RECABOOL, "WEG Verwaltung
         PARTNER        TYPE  BU_PARTNER,
         TITLE_MEDI     TYPE AD_TITLETX,
         NAME_FIRST     TYPE BU_NAMEP_F,
         NAME_LAST      TYPE  BU_NAMEP_L,
         XPARTNER       TYPE  REBPXPARTNER,
         CITY1          TYPE AD_CITY1,
         POST_CODE      TYPE AD_PSTCD1,
         STREET         TYPE AD_STREET,
         HOUSE_NUM1     TYPE AD_HSNM1,
         BIRTHDT        TYPE  BU_BIRTHDT,
         AVAIL_FROM     TYPE NUMC2,
         AVAIL_TO       TYPE NUMC2,
         PHONE1         TYPE AD_TLNMBR,
         MOBILE1        TYPE  AD_TLNMBR,
         E_MAIL         TYPE  AD_SMTPADR,
         DEBITOR        TYPE  KUNNR,
         IDENTKEY       TYPE  RECAIDENTKEY,
         ADDRESS        TYPE  CHAR128,
         SSTOCKW        TYPE VVSSTOCKW,
         XSTOCKL        TYPE  XGMBEZ,
         RLGESCH        TYPE RLGESCH,
         XMLGESCH       TYPE XMLGESCH,
         YBAUJAHR       TYPE  VVYBAUJAHR,
         MEASVALUE      TYPE REBDMEASVALUE,
         STTXT_INT      TYPE CO_STTXT,
         OBJNR_BE       TYPE RECAOBJNR,
         OBJNR_BU       TYPE RECAOBJNR,
         OBJNR_PR       TYPE RECAOBJNR,
         OBJNR_RO       TYPE RECAOBJNR,
         OBJNR          TYPE RECAOBJNR,
*         ih_stopp                TYPE zih_stopp,
*         ih_kommentar            TYPE zkommentar,
*         zreca_status_txt        TYPE zreca_status_txt,
         STATUS         TYPE J_TXT30,
       END OF TT_RECN.
* Data aufbauen
DATA:
  GT_RECN           TYPE TABLE OF TT_RECN,
  GS_RECN           LIKE LINE OF GT_RECN,
* gt_vicncn TYPE TABLE OF vicncn,
  GT_TIV2F          TYPE TABLE OF TIV2F,
  GS_HEIZUNG_DIALOG TYPE ZST_HEIZUNG_DIALOG,
  GS_VIBDBU         TYPE VIBDBU.
* Partner
DATA:
  GT_PARTNER        TYPE          BAPI_RE_T_PARTNER_INT,
  GS_PARTNER        LIKE LINE OF  GT_PARTNER,
  GT_CLERK_BAPI     TYPE          BAPI_RE_T_PARTNER_INT,
  GS_CLERK_BAPI     LIKE LINE OF  GT_CLERK_BAPI,
  GS_CONTRACT       TYPE BAPI_RE_CONTRACT_INT,
  GD_HANWERKER_NAME TYPE REBPXNAME,
  GD_OBJNR_TPL_RO   TYPE TPLNR,
  GD_OBJNR_TPL_BU   TYPE TPLNR,
  GD_TP_TXT(8).
*  gs_bupa_data  TYPE  /promos/s_bupa_data.

* Mitarbeiter
DATA:
  BEGIN OF GS_CLERK,
    PARTNER_CLERK TYPE  BU_PARTNER,
    XNAME         TYPE  REBPXNAME,
    TELEFON       TYPE  AD_TLNMBR1,
    SMTP_ADDR     TYPE  AD_SMTPADR,
    YYMOB_NUMBER  TYPE  AD_TLNMBR,
    XPARTNER      TYPE  REBPXPARTNER,
    VALIDFROM     TYPE  REBPVALIDFROM,
    VALIDTO       TYPE  REBPVALIDTO,
    ROLE          TYPE  REBPROLE,
    RLTXT         TYPE  BU_PARTNERROLETXT,
  END OF GS_CLERK,
  GT_CLERK LIKE TABLE OF GS_CLERK,
* Partner
  BEGIN OF GS_PARTNER_CN,
    PARTNER   TYPE  BU_PARTNER,
    ROLE      TYPE  REBPROLE,
    XNAME     TYPE  REBPXNAME,
    XPARTNER  TYPE  REBPXPARTNER,
    VALIDFROM TYPE  REBPVALIDFROM,
    VALIDTO   TYPE  REBPVALIDTO,
  END OF GS_PARTNER_CN,
  GT_PARTNER_CN LIKE TABLE OF GS_PARTNER_CN.
* Konditionen
DATA:
  BEGIN OF GS_COND,
    CONDTYPE         TYPE  RECDCONDTYPE,
    CONDVALIDFROM    TYPE  RECDVALIDFROM,
    XCONDITION       TYPE RECDXCONDITION,
    UNITPRICE        TYPE RECDUNITPRICE,
    OBJIDENTCALC     TYPE REBDOBJECTIDENTCALC,
    CONDVALIDTO      TYPE  RECDVALIDTO,
    XMCONDPURPOSEEXT TYPE RECDXMCONDPURPOSEEXT,
    XTAXGROUP        TYPE RERAXMTAXGROUP,
    T_COLOR          TYPE LVC_T_SCOL,
  END OF GS_COND,
  GT_COND LIKE TABLE OF GS_COND.
* Belegung
DATA:
  BEGIN OF GS_OCCUPANCY,
    IDENTKEY_RO TYPE RECAIDENTKEY, "Mietobjekt
    XMETXT      TYPE REBDXRO,
    OCCFROM     TYPE REBDOCCFROM,
    OCCTO       TYPE REBDOCCTO,
    IDENTKEY_CN TYPE RECAIDENTKEY, "Vertrag
    RECNTXT	    TYPE RECNTXT,
    OBJNR_RO    TYPE RECAOBJNR,
    OBJNR_CN    TYPE RECAOBJNR,
  END OF GS_OCCUPANCY,
  GT_OCCUPANCY LIKE TABLE OF GS_OCCUPANCY.
* Wartungsverträge
DATA:
  BEGIN OF GS_WARTUNG,
    IDENTKEY_RO TYPE RECAIDENTKEY.
    INCLUDE STRUCTURE ZST_WARTBEST_UEB.
  DATA:
  END OF GS_WARTUNG,
  GT_WARTUNG LIKE TABLE OF GS_WARTUNG. "Mietobjekte

* Gebäude
DATA:
  BEGIN OF GS_WARTUNG_GEB,
    IDENTKEY_BU TYPE RECAIDENTKEY.
    INCLUDE STRUCTURE ZST_WARTBEST_UEB.
    DATA: TELF1       TYPE LFA1-TELF1,
    TELFX       TYPE LFA1-TELFX,
    SMTP_ADDR   TYPE  AD_SMTPADR,
  END OF GS_WARTUNG_GEB,
  GT_WARTUNG_GEB LIKE TABLE OF GS_WARTUNG_GEB. "Gebäude

* Wirtschaftseinheit
DATA:
  BEGIN OF GS_WARTUNG_WE,
    IDENTKEY_WE TYPE RECAIDENTKEY,
    DOC_WART    TYPE RERADOCITEMID.
    INCLUDE     STRUCTURE ZST_WARTBEST_UEB.
    DATA: TELF1       TYPE LFA1-TELF1,
    TELFX       TYPE LFA1-TELFX,
    SMTP_ADDR   TYPE  AD_SMTPADR,
  END OF GS_WARTUNG_WE,
  GT_WARTUNG_WE LIKE TABLE OF GS_WARTUNG_WE. "Wirtschaftseinheit

* Ausstattungsmerkmale WE
DATA:
  BEGIN OF GS_CHARACT_BE,
    IDENTKEY_BE    TYPE RECAIDENTKEY,
    XFIXFITCHARACT TYPE REBDXFIXFITCHARACT,
    VALIDTO        TYPE  REBDVALIDTO.
    INCLUDE STRUCTURE VIBDCHARACT_TAB.
  DATA:
  END OF GS_CHARACT_BE,
  GT_CHARACT_BE LIKE TABLE OF GS_CHARACT_BE.

* Ausstattungsmerkmale Gebäude
DATA:
  BEGIN OF GS_CHARACT,
    IDENTKEY_BU    TYPE RECAIDENTKEY,
    XFIXFITCHARACT TYPE REBDXFIXFITCHARACT,
    VALIDTO        TYPE  REBDVALIDTO.
    INCLUDE STRUCTURE VIBDCHARACT_TAB.
  DATA:
  END OF GS_CHARACT,
  GT_CHARACT LIKE TABLE OF GS_CHARACT.

* Ausstattungsmerkmale Mietobjekt
DATA:
  BEGIN OF GS_CHARACT_RO,
    IDENTKEY_RO    TYPE RECAIDENTKEY,
    XFIXFITCHARACT TYPE REBDXFIXFITCHARACT,
    VALIDTO        TYPE  REBDVALIDTO.
    INCLUDE STRUCTURE VIBDCHARACT_TAB.
  DATA:
  END OF GS_CHARACT_RO,
  GT_CHARACT_RO LIKE TABLE OF GS_CHARACT_RO.

* MO pro Gebäude
DATA:
  BEGIN OF GS_RO,
    IDENTKEY_RO_RO TYPE RECAIDENTKEY, "Mietobjekt
    XMETXT         TYPE REBDXRO,
    IDENTKEY_CN_RO TYPE RECAIDENTKEY, "Vertrag
    RECNTXT	       TYPE RECNTXT,
    RECNBEG        TYPE RECNCNBEG,
    RECNENDABS     TYPE RECNCNENDABS,
    MEASVALUE	     TYPE REBDMEASVALUE,
    KELLERNR       TYPE CHAR25,
    XNAME          TYPE  REBPXNAME,
    TELEFON        TYPE AD_TLNMBR1,
    SSTOCKW        TYPE VVSSTOCKW,
    XSTOCKL        TYPE  XGMBEZ,
    RLGESCH        TYPE RLGESCH,
    XMLGESCH       TYPE XMLGESCH,
    OBJNR_RO       TYPE RECAOBJNR,
    OBJNR_CN       TYPE RECAOBJNR,
    INTRENO_CN     TYPE VVINTRENO,
  END OF GS_RO,
  GT_RO LIKE TABLE OF GS_RO.
* Flächen
DATA:
  BEGIN OF GS_AREA,
    MEAS      TYPE  REBDMEAS,
    VALIDFROM TYPE  REBDMEASVALIDFROM,
    VALIDTO   TYPE REBDMEASVALIDTO,
    MEASVALUE TYPE REBDMEASVALUE,
    XMMEAS    TYPE REBDXMMEAS,
    MEASUNIT  TYPE REBDMEASUNIT,
  END OF GS_AREA,
  GT_AREA LIKE TABLE OF GS_AREA.
* Kessel angeschlosssene Objekte
DATA:
  BEGIN OF GS_KESSEL,
    ANLAGEN_ID  LIKE ZPD_ZTHEIZ_ANGSL-ANLAGEN_ID, " E.FIrsanov 15.07.2024
    AUSGSL      LIKE ZPD_ZTHEIZ_ANGSL-AUSGSL, " E.FIrsanov 15.07.2024
    FREMD       LIKE ZPD_ZTHEIZ_ANGSL-FREMD, " E.FIrsanov 15.07.2024
    CITY1       LIKE ZPD_ZTHEIZ_ANGSL-CITY1, " E.FIrsanov 15.07.2024
    POST_CODE1  LIKE ZPD_ZTHEIZ_ANGSL-POST_CODE1, " E.FIrsanov 15.07.2024
    XGEBK       LIKE ZPD_ZTHEIZ_ANGSL-XGEBK, " E.FIrsanov 15.07.2024
    STREET      LIKE ZPD_ZTHEIZ_ANGSL-STREET, " E.FIrsanov 15.07.2024
    HOUSE_NUM1  LIKE ZPD_ZTHEIZ_ANGSL-HOUSE_NUM1, " E.FIrsanov 15.07.2024
    ANZ_WO_BEST LIKE ZPD_ZTHEIZ_ANGSL-ANZ_WO_BEST, " E.FIrsanov 15.07.2024
    ANZ_GEWERBE LIKE ZPD_ZTHEIZ_ANGSL-ANZ_GEWERBE, " E.FIrsanov 15.07.2024
    ANZ_GARAGE  LIKE ZPD_ZTHEIZ_ANGSL-ANZ_GARAGE, " E.FIrsanov 15.07.2024
    HEIZFLAECHE LIKE ZPD_ZTHEIZ_ANGSL-HEIZFLAECHE, " E.FIrsanov 15.07.2024
    MEASUNIT    LIKE ZPD_ZTHEIZ_ANGSL-MEASUNIT, " E.FIrsanov 15.07.2024
    BUKRS       LIKE ZPD_ZTHEIZ_ANGSL-BUKRS, " E.FIrsanov 15.07.2024
    SWENR       LIKE ZPD_ZTHEIZ_ANGSL-SWENR, " E.FIrsanov 15.07.2024
    SGENR       LIKE ZPD_ZTHEIZ_ANGSL-SGENR, " E.FIrsanov 15.07.2024
    HOUSE_NUM2  LIKE ZPD_ZTHEIZ_ANGSL-HOUSE_NUM2, " E.FIrsanov 15.07.2024
  END OF GS_KESSEL,
  GT_KESSEL LIKE TABLE OF GS_KESSEL.
* Notdienst
DATA:
  BEGIN OF GS_NOTDIENST,
    ZZLIFNR   LIKE ZPMHW-ZZLIFNR,
    NAME1     LIKE LFA1-NAME1,
    TELF1     LIKE LFA1-TELF1,
    TELF_NOT  LIKE LFA1-TELF1,
    STRAS     LIKE LFA1-STRAS,
    PSTLZ     LIKE LFA1-PSTLZ,
    ORT01     LIKE LFA1-ORT01,
    SMTP_ADDR TYPE  AD_SMTPADR,
    ZZREGIO   LIKE ZPMHW-ZZREGIO,
    ZZPRCTR   LIKE ZPMHW-ZZPRCTR,
    ZZMATKL   LIKE ZPMHW-ZZMATKL,
    WGBEZ     TYPE WGBEZ,
    ZZHWK     LIKE ZPMHW-ZZHWK,
    ZZREP     LIKE ZPMHW-ZZREP,
    ZZEZM     LIKE ZPMHW-ZZEZM,
    ZZNOTKZ   LIKE ZPMHW-ZZNOTKZ,
    ZZVERS    LIKE ZPMHW-ZZVERS,
    ZZLAW     LIKE ZPMHW-ZZLAW,
    ZZRABATT  LIKE ZPMHW-ZZRABATT,
    ZZVODAT   LIKE ZPMHW-ZZVODAT,
    ZZBIDAT   LIKE ZPMHW-ZZBIDAT,
  END OF GS_NOTDIENST,
  GT_NOTDIENST LIKE TABLE OF GS_NOTDIENST.

* Bestellungen
DATA:
  BEGIN OF GS_BESTELLUNG,
    EBELN       TYPE EBELN,
    EBELP       TYPE EBELP,
*    perio       TYPE co_perio,
*    gjahr       TYPE gjahr,
*    loekz       TYPE eloek,
*    erekz       TYPE erekz,
    DOC_BEST    TYPE RERADOCITEMID,
    NETPR       TYPE BPREI,
    BRTWR       TYPE BRTWR,
    KZWI2       TYPE KZWI2, "Nachtrag
    KZWI4       TYPE KZWI4, "Abschlag
    TXZ01       TYPE TXZ01,
    IDENTKEY_RE TYPE RECAIDENTKEY, "RE-Objekt
    MATKL       TYPE  MATKL,
    WGBEZ       TYPE  WGBEZ,
    LIFNR       TYPE  LIFNR,
    NAME1       TYPE  NAME1_GP,
    POST_CODE1  TYPE  AD_PSTCD1,
    CITY1       TYPE  AD_CITY1,
    STREET      TYPE  AD_STREET,
    HOUSE_NUM1  TYPE  AD_HSNM1,
    OBJNR_BEST  TYPE  J_OBJNR,
    TELF1       TYPE LFA1-TELF1,
    TELFX       TYPE LFA1-TELFX,
    SMTP_ADDR   TYPE  AD_SMTPADR,

  END OF GS_BESTELLUNG,
  GT_BESTELLUNG LIKE TABLE OF GS_BESTELLUNG.

*&SPWIZARD: FUNCTION CODES FOR TABSTRIP 'TABS_INFO'
CONSTANTS: BEGIN OF C_TABS_INFO,
             TAB1 LIKE SY-UCOMM VALUE 'TABS_INFO_FC1',
             TAB2 LIKE SY-UCOMM VALUE 'TABS_INFO_FC2',
             TAB3 LIKE SY-UCOMM VALUE 'TABS_INFO_FC3',
             TAB4 LIKE SY-UCOMM VALUE 'TABS_INFO_FC4',
           END OF C_TABS_INFO.
*&SPWIZARD: DATA FOR TABSTRIP 'TABS_INFO'
CONTROLS:  TABS_INFO TYPE TABSTRIP.
DATA: BEGIN OF G_TABS_INFO,
        SUBSCREEN   LIKE SY-DYNNR,
        PROG        LIKE SY-REPID VALUE 'SAPLZRE_PM_COCKPIT',
        PRESSED_TAB LIKE SY-UCOMM VALUE C_TABS_INFO-TAB1,
      END OF G_TABS_INFO.
DATA:      GV_OK_CODE_TAB LIKE SY-UCOMM.
* Belegung

DATA:
  GT_OCCUPANCY_X   TYPE RE_T_OCCUPANCY_X,
  GT_OCCUPANCY_ALV TYPE STANDARD TABLE OF REBD_OCCUPANCY_L.

*=======================================================================
DATA:         " E.Firsanov gui information (buffered for pbo processing only)
*=======================================================================
  BEGIN OF GS_GUI,
    SUBSCREEN TYPE RECASCREEN,
  END OF GS_GUI,
  GS_INFO_CONTEXT_ZUSATZ TYPE ZST_INFO_CONTEXT_ZUSATZ.

TABLES: ZST_INFO_CONTEXT.



* lokale Klassen
INCLUDE LZRE_PM_COCKPITD01.
