PROCESS BEFORE OUTPUT.
  MODULE status_0100.
  MODULE pbo_0100.
  MODULE modify_screen_0100.
  CALL SUBSCREEN sub_cn
       INCLUDING 'SAPLZRECN_BP_COCKPIT' gd_dyn_cn.
  CALL SUBSCREEN zusatz
       INCLUDING 'SAPLZRECN_BP_COCKPIT'
                 '5050'.
PROCESS AFTER INPUT.
  CALL SUBSCREEN sub_cn.
  MODULE pai_0100.
