PROCESS BEFORE OUTPUT.
  MODULE status_0220.
  MODULE pbo_0220.
*
PROCESS AFTER INPUT.
  MODULE user_command_0200 AT EXIT-COMMAND.
  CHAIN.
    FIELD  gs_dynpro_cn_02-code
    MODULE set_code ON INPUT.
  ENDCHAIN.
  MODULE pai_0300.

*PROCESS ON VALUE-REQUEST.
*  FIELD gs_dynpro_cn_01-code MODULE set_code.
